GET http://localhost:3000/usuario/

###
GET http://localhost:3000/usuario/1

###
POST http://localhost:3000/usuario/
Content-Type: application/json

{
    "nombre": "anglito",
    "apellido": "Doe",
    "edad": 25,
    "sexo": "M",
    "pais": "USA",
    "email": "john.doe@example.com",
    "activo": true
}

###
PATCH  http://localhost:3000/usuario/1
Content-Type: application/json

{
    "nombre": "anglito",
    "apellido": "Doe",
    "edad": 25,
    "sexo": "M",
    "pais": "USA",
    "email": "john.doe@example.com",
    "activo": true
}

###
DELETE http://localhost:3000/usuario/1